name: Generate Dokka Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LootGoblin
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" 
          java-version: "18"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Documentation
        run: ./gradlew dokkaHtml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs
