name: Publish Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "18"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Upload release
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_SECRET }}

      - name: Publish release
        run: ./gradlew closeAndReleaseRepository --no-daemon --no-parallel --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}